name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v3
      #----------------------------------------------
      #           execute format with ruff
      #----------------------------------------------
      - uses: chartboost/ruff-action@v1
        with:
          args: check --fix-only --unsafe-fixes --show-fixes
      #----------------------------------------------
      #              save ruff changes
      #----------------------------------------------
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Ruff Action -> Fixing linting errors
